#Essence Config

#General Navigator Settings
navigator:
  name: "&cNavigator"
  inv-slot: 4
  inv-size: 27

#Navigator Content
navigator-warps:
  - spawn:
      slot: 1
      id: SLIME_BALL
      name: 'Spawn'
      coordinates:
        x: 0
        y: 60
        z: 0
      lore:
        - 'hubby hubby hub'