main: essence.Main
version: 0.1
name: Essence
authors: [JustFloooo, Nicronicson]
api-version: 1.13
commands:
  gm:
    description: Fast gamemode switcher
    usage: /gm [0-3]
  v:
    description: Make yourself invisible to others
    usage: /v