main: essence.Main
version: 0.1
name: Essence
authors: [JustFloooo, Nicronicson]
api-version: 1.13
commands:
  gm:
    description: Fast gamemode switcher
    usage: /gm [0-3]
    permission: essence.command.gm
  v:
    description: Make yourself invisible to others
    usage: /v [PlayerName] [s]
    aliases: vanish
    permission: essence.command.vanish
  s:
    description: Change your speed
      usage: /s [speed]
      aliases: speed
      permission: essence.command.speed
permissions:
  essence.command.gm:
    default: op
  essence.command.vanish:
    default: op
  essence.command.speed:
    default: op